-- PROCEDURE TO LIST ALL TRIGGERS ON THE SERVER --
DROP PROCEDURE IF EXISTS `dbatools`.`TRIGGER_LIST_ALL`;
DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `TRIGGER_LIST_ALL`()
  COMMENT 'Lists all triggers on the server.'
proc_label:BEGIN
  SELECT TRIGGER_NAME, TRIGGER_SCHEMA, DEFINER FROM INFORMATION_SCHEMA.TRIGGERS ORDER BY TRIGGER_SCHEMA, TRIGGER_NAME;
END$$
DELIMITER ;
-- END

-- PROCEDURE TO LIST ALL TRIGGERS IN A SCHEMA --
DROP PROCEDURE IF EXISTS `dbatools`.`TRIGGER_LIST_SCHEMA`;
DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `TRIGGER_LIST_SCHEMA`(
  IN q_schema CHAR(64))
  COMMENT 'Lists all triggers in a schema.'
proc_label:BEGIN

IF q_schema IS NULL OR q_schema = '' THEN
  SELECT "ERROR: ARGV1 not set. Specify a schema via 'call TRIGGER_LIST_SCHEMA('foo');'";
  LEAVE proc_label;

 ELSE
  SELECT TRIGGER_NAME, TRIGGER_SCHEMA, DEFINER FROM INFORMATION_SCHEMA.TRIGGERS WHERE TRIGGER_SCHEMA = q_schema ORDER BY TRIGGER_NAME, TRIGGER_SCHEMA;
 END IF;

END$$
DELIMITER ;
-- END

-- PROCEDURE TO SEARCH ONE TRIGGER BY NAME --
DROP PROCEDURE IF EXISTS `dbatools`.`TRIGGER_SEARCH`;
DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `TRIGGER_SEARCH`(
  IN q_trigger CHAR(64))
  COMMENT 'Searches for a trigger by name.'
proc_label:BEGIN

IF q_trigger IS NULL OR q_trigger = '' THEN
  SELECT "ERROR: ARGV1 not set. Specify a trigger via 'call TRIGGER_SEARCH('foo');'";
  LEAVE proc_label;

 ELSE
  SELECT TRIGGER_NAME, TRIGGER_SCHEMA, DEFINER FROM INFORMATION_SCHEMA.TRIGGERS WHERE TRIGGER_NAME LIKE CONCAT('%', q_trigger , '%') ORDER BY TRIGGER_NAME, TRIGGER_SCHEMA;
 END IF;

END$$
DELIMITER ;
-- END

-- PROCEDURE TO LIST ALL PROCEDURE ON THE SERVER --
DROP PROCEDURE IF EXISTS `dbatools`.`PROC_LIST_ALL`;
DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `PROC_LIST_ALL`()
  COMMENT 'Lists all PROCEDURES on the server.'
proc_label:BEGIN
  SELECT ROUTINE_NAME, ROUTINE_SCHEMA, DEFINER FROM INFORMATION_SCHEMA.ROUTINES ORDER BY ROUTINE_SCHEMA, ROUTINE_NAME;
END$$
DELIMITER ;
-- END

-- PROCEDURE TO LIST ALL TRIGGERS IN A SCHEMA --
DROP PROCEDURE IF EXISTS `dbatools`.`PROC_LIST_SCHEMA`;
DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `PROC_LIST_SCHEMA`(
  IN q_schema CHAR(64))
  COMMENT 'Lists all PROCEDURES in a schema.'
proc_label:BEGIN

IF q_schema IS NULL OR q_schema = '' THEN
  SELECT "ERROR: ARGV1 not set. Specify a schema via 'call PROC_LIST_SCHEMA('foo');'";
  LEAVE proc_label;

 ELSE
  SELECT ROUTINE_NAME, ROUTINE_SCHEMA, DEFINER FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA = q_schema ORDER BY ROUTINE_SCHEMA, ROUTINE_NAME;
 END IF;

END$$
DELIMITER ;
-- END

-- PROCEDURE TO SEARCH ONE TRIGGER BY NAME --
DROP PROCEDURE IF EXISTS `dbatools`.`PROC_SEARCH`;
DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `PROC_SEARCH`(
  IN q_proc CHAR(64))
  COMMENT 'Searches for a PROCEDURE by name.'
proc_label:BEGIN

IF q_proc IS NULL OR q_proc = '' THEN
  SELECT "ERROR: ARGV1 not set. Specify a trigger via 'call PROC_SEARCH('foo');'";
  LEAVE proc_label;

 ELSE
  SELECT ROUTINE_NAME, ROUTINE_SCHEMA, DEFINER FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_NAME LIKE CONCAT('%', q_proc , '%') ORDER BY ROUTINE_SCHEMA, ROUTINE_NAME;
 END IF;

END$$
DELIMITER ;
-- END
